spring:
  datasource:
    username: root
    password: zhang2001228
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: library.demo.pojo
  mapper-locations: classpath:mapper/*.xml
